[package]
name = "mixer_chat"
version = "0.1.0"
authors = ["Innectic <innectic@gmail.com>"]

[dependencies]
serde = "1.0.84"
serde_json = "1.0.34"
serde_derive = "1.0.84"
reqwest = "0.9.5"
env_logger = "0.6.0"
websocket = "0.22.1"
