[package]
name = "mixer_chat"
version = "0.1.0"
authors = ["Innectic <innectic@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.8.8"
maplit = "1.0.1"
env_logger = "0.5.13"
websocket = "*"
zmq = "*"
